#!/bin/bash
#
DIRFTP=/mma/datos/ftproot/EXPL
DIRANA=/mma/datos/kiuwanSubsistemas/EXPL

# $1 directorio Origen
# $2 extension
# $3 directorio Destino
# actualiza ACCIDENT_BATCD BATCD APLICACIONES-ACCIDENTES_BATCD
function actualiza {
	echo "Actualizando $DIRANA/$3 ..." 
	for f in `ls $DIRFTP/$1|grep -v "\."`; do 
		echo "Actualizando $DIRANA/$3/$f.$2 .."
		cp $DIRFTP/$1/$f $DIRANA/$3/$f.$2; 
	done
}

function analiza {
cd /mma/datos/Analizadores/EXPL/bin
./agent.sh -n $3 -c $3 -s $DIRANA/$3
}

function analizaSemanal {
cd /mma/datos/Analizadores/EXPL/bin
./agent.sh -n $1 -c $1 -s $DIRANA/$1
}

# Analisis Semanal Baseline 2017.01.22
analizaSemanal APLICACIONES-AUTOS-PRESTACIONES_BATCD
#analizaSemanal APLICACIONES-AUTOS-PRESTACIONES_CICSD
#analizaSemanal APLICACIONES-AUTOS-PRODUCCION_BATCD
analizaSemanal APLICACIONES-AUTOS-PRODUCCION_CICSD
analizaSemanal APLICACIONES-AUTOS-PRODUCCION_MODUD
analizaSemanal APLICACIONES-COMUNES_CICSD
analizaSemanal APLICACIONES-HOGAR-PRESTACIONES_CICS
#analizaSemanal APLICACIONES-HOGAR-PRESTACIONES_MODUD
analizaSemanal APLICACIONES-HOGAR-PRODUCCION_CICS
analizaSemanal APLICACIONES-HOGAR-PRODUCCION_CICSD
#analizaSemanal APLICACIONES-OTROS-RAMOS_BATCD
#analizaSemanal APLICACIONES-VIDA_BATCD
#analizaSemanal APLICACIONES-VIDA_CICSD

# No analizamos por CTM
#analizaSemanal SIN-CATALOGAR_BATCD
#analizaSemanal SIN-CATALOGAR_CICS
#analizaSemanal SIN-CATALOGAR_CICSD
#analizaSemanal SIN-CATALOGAR_MODU
#analizaSemanal SIN-CATALOGAR_MODUD




# Actualizamos 2017.01.22 
#actualiza ASISTEN_MODUD MODUD APLICACIONES-ASISTENCIA_MODUD
#actualiza AUPREST_CICSD CICSD APLICACIONES-AUTOS-PRESTACIONES_CICSD
#actualiza AUPRODU_BATC BATC APLICACIONES-AUTOS-PRODUCCION_BATC
#actualiza AUPRODU_BATCD BATCD APLICACIONES-AUTOS-PRODUCCION_BATCD
#actualiza COMUNES_BATCD BATCD APLICACIONES-COMUNES_BATCD
#actualiza COMUNES_MODUD MODUD APLICACIONES-COMUNES_MODUD
#actualiza HOGPREST_MODUD MODUD APLICACIONES-HOGAR-PRESTACIONES_MODUD
#actualiza HOGPRODU_BATCD BATCD APLICACIONES-HOGAR-PRODUCCION_BATCD
#actualiza OTRAMOS_BATCD BATCD APLICACIONES-OTROS-RAMOS_BATCD
#actualiza SINCATLG_MODUD MODUD SIN-CATALOGAR_MODUD
#actualiza VIDA_BATC BATC APLICACIONES-VIDA_BATC
#actualiza VIDA_BATCD BATCD APLICACIONES-VIDA_BATCD
#actualiza VIDA_CICSD CICSD APLICACIONES-VIDA_CICSD

# Analizamos 2017.01.22
#analiza ASISTEN_MODUD MODUD APLICACIONES-ASISTENCIA_MODUD
#analiza AUPREST_CICSD CICSD APLICACIONES-AUTOS-PRESTACIONES_CICSD
#analiza AUPRODU_BATC BATC APLICACIONES-AUTOS-PRODUCCION_BATC
#analiza AUPRODU_BATCD BATCD APLICACIONES-AUTOS-PRODUCCION_BATCD
#analiza COMUNES_BATCD BATCD APLICACIONES-COMUNES_BATCD
#analiza COMUNES_MODUD MODUD APLICACIONES-COMUNES_MODUD
#analiza HOGPREST_MODUD MODUD APLICACIONES-HOGAR-PRESTACIONES_MODUD
#analiza HOGPRODU_BATCD BATCD APLICACIONES-HOGAR-PRODUCCION_BATCD
#analiza OTRAMOS_BATCD BATCD APLICACIONES-OTROS-RAMOS_BATCD
##analiza SINCATLG_MODUD MODUD SIN-CATALOGAR_MODUD
#analiza VIDA_BATC BATC APLICACIONES-VIDA_BATC
#analiza VIDA_BATCD BATCD APLICACIONES-VIDA_BATCD
#analiza VIDA_CICSD CICSD APLICACIONES-VIDA_CICSD


# Copiamos y Analizamos 
#analiza ACCIDENT_BATCD BATCD APLICACIONES-ACCIDENTES_BATCD
#analiza ACCIDENT_CICSD CICSD APLICACIONES-ACCIDENTES_CICSD
#analiza ACCIDENT_MODU MODU APLICACIONES-ACCIDENTES_MODU
#analiza ACCIDENT_MODUD MODUD APLICACIONES-ACCIDENTES_MODUD
#analiza ACTUARIA_BATCD BATCD APLICACIONES-ACTUARIAL_BATCD
#analiza ACTUARIA_CICS CICS APLICACIONES-ACTUARIAL_CICS
#analiza ACTUARIA_CICSD CICSD APLICACIONES-ACTUARIAL_CICSD
#analiza ACTUARIA_MODU MODU APLICACIONES-ACTUARIAL_MODU
#analiza ACTUARIA_MODUD MODUD APLICACIONES-ACTUARIAL_MODUD
#analiza ACTUARIA_MQS MQS APLICACIONES-ACTUARIAL_MQS
#analiza ACTUARIA_MQSBAT MQSBAT APLICACIONES-ACTUARIAL_MQSBAT
#analiza ASISTEN_BATC BATC APLICACIONES-ASISTENCIA_BATC
#analiza ASISTEN_BATCD BATCD APLICACIONES-ASISTENCIA_BATCD
#analiza ASISTEN_CICS CICS APLICACIONES-ASISTENCIA_CICS
#analiza ASISTEN_CICSD CICSD APLICACIONES-ASISTENCIA_CICSD
#analiza ASISTEN_MODU MODU APLICACIONES-ASISTENCIA_MODU
#analiza ASISTEN_MODUD MODUD APLICACIONES-ASISTENCIA_MODUD
#analiza AUGRCUEN_BATCD BATCD APLICACIONES-AUTOS-GRANDES-CUENTAS_BATCD
#analiza AUGRCUEN_CICS CICS APLICACIONES-AUTOS-GRANDES-CUENTAS_CICS
#analiza AUGRCUEN_CICSD CICSD APLICACIONES-AUTOS-GRANDES-CUENTAS_CICSD
#analiza AUGRCUEN_MODUD MODUD APLICACIONES-AUTOS-GRANDES-CUENTAS_MODUD
#analiza AUPREST_BATC BATC APLICACIONES-AUTOS-PRESTACIONES_BATC
#analiza AUPREST_BATCD BATCD APLICACIONES-AUTOS-PRESTACIONES_BATCD
#analiza AUPREST_CICS CICS APLICACIONES-AUTOS-PRESTACIONES_CICS
#analiza AUPREST_CICSD CICSD APLICACIONES-AUTOS-PRESTACIONES_CICSD
#analiza AUPREST_MODU MODU APLICACIONES-AUTOS-PRESTACIONES_MODU
#analiza AUPREST_MODUD MODUD APLICACIONES-AUTOS-PRESTACIONES_MODUD
#analiza AUPREST_MQS MQS APLICACIONES-AUTOS-PRESTACIONES_MQS
#analiza AUPREST_MQSBAT MQSBAT APLICACIONES-AUTOS-PRESTACIONES_MQSBAT
#analiza AUPRODU_BATC BATC APLICACIONES-AUTOS-PRODUCCION_BATC
#analiza AUPRODU_BATCD BATCD APLICACIONES-AUTOS-PRODUCCION_BATCD
#analiza AUPRODU_CICS CICS APLICACIONES-AUTOS-PRODUCCION_CICS
#analiza AUPRODU_CICSD CICSD APLICACIONES-AUTOS-PRODUCCION_CICSD
#analiza AUPRODU_MODU MODU APLICACIONES-AUTOS-PRODUCCION_MODU
#analiza AUPRODU_MODUD MODUD APLICACIONES-AUTOS-PRODUCCION_MODUD
#analiza CALIDAD_BATC BATC APLICACIONES-CALIDAD_BATC
#analiza CALIDAD_BATCD BATCD APLICACIONES-CALIDAD_BATCD
#analiza CALIDAD_CICS CICS APLICACIONES-CALIDAD_CICS
#analiza CALIDAD_CICSD CICSD APLICACIONES-CALIDAD_CICSD
#analiza CALIDAD_MODU MODU APLICACIONES-CALIDAD_MODU
#analiza CALIDAD_MODUD MODUD APLICACIONES-CALIDAD_MODUD
#analiza CALIDAD_MQS MQS APLICACIONES-CALIDAD_MQS
#analiza CALIDAD_MQSBAT MQSBAT APLICACIONES-CALIDAD_MQSBAT
#analiza COMUNES_BATC BATC APLICACIONES-COMUNES_BATC
#analiza COMUNES_BATCD BATCD APLICACIONES-COMUNES_BATCD
#analiza COMUNES_CICS CICS APLICACIONES-COMUNES_CICS
#analiza COMUNES_CICSD CICSD APLICACIONES-COMUNES_CICSD
#analiza COMUNES_MODU MODU APLICACIONES-COMUNES_MODU
#analiza COMUNES_MODUD MODUD APLICACIONES-COMUNES_MODUD
#analiza COMUNES_MQS MQS APLICACIONES-COMUNES_MQS
#analiza COMUNES_MQSBAT MQSBAT APLICACIONES-COMUNES_MQSBAT
#analiza CPROYTI_BATC BATC CENTRO-DE-PROYECTOS-TI_BATC
#analiza CPROYTI_BATCD BATCD CENTRO-DE-PROYECTOS-TI_BATCD
#analiza CPROYTI_CICS CICS CENTRO-DE-PROYECTOS-TI_CICS
#analiza CPROYTI_MODUD MODUD CENTRO-DE-PROYECTOS-TI_MODUD
#analiza ETL_BATCD BATCD APLICACIONES-ETL_BATCD
#analiza HOGPREST_BATCD BATCD APLICACIONES-HOGAR-PRESTACIONES_BATCD
#analiza HOGPREST_CICS CICS APLICACIONES-HOGAR-PRESTACIONES_CICS
#analiza HOGPREST_CICSD CICSD APLICACIONES-HOGAR-PRESTACIONES_CICSD
#analiza HOGPREST_MODU MODU APLICACIONES-HOGAR-PRESTACIONES_MODU
#analiza HOGPREST_MODUD MODUD APLICACIONES-HOGAR-PRESTACIONES_MODUD
#analiza HOGPRODU_BATC BATC APLICACIONES-HOGAR-PRODUCCION_BATC
#analiza HOGPRODU_BATCD BATCD APLICACIONES-HOGAR-PRODUCCION_BATCD
#analiza HOGPRODU_CICS CICS APLICACIONES-HOGAR-PRODUCCION_CICS
#analiza HOGPRODU_CICSD CICSD APLICACIONES-HOGAR-PRODUCCION_CICSD
#analiza HOGPRODU_MODU MODU APLICACIONES-HOGAR-PRODUCCION_MODU
#analiza HOGPRODU_MODUD MODUD APLICACIONES-HOGAR-PRODUCCION_MODUD
#analiza MODUCOM_BATC BATC APLICACIONES-MODULOS-COMUNES_BATC
#analiza MODUCOM_BATCD BATCD APLICACIONES-MODULOS-COMUNES_BATCD
#analiza MODUCOM_CICS CICS APLICACIONES-MODULOS-COMUNES_CICS
#analiza MODUCOM_CICSD CICSD APLICACIONES-MODULOS-COMUNES_CICSD
#analiza MODUCOM_MODU MODU APLICACIONES-MODULOS-COMUNES_MODU
#analiza MODUCOM_MODUD MODUD APLICACIONES-MODULOS-COMUNES_MODUD
#analiza MUTUACTV_CICSD CICSD APLICACIONES-MUTUACTIVOS_CICSD
#analiza OTRAMOS_BATC BATC APLICACIONES-OTROS-RAMOS_BATC
#analiza OTRAMOS_BATCD BATCD APLICACIONES-OTROS-RAMOS_BATCD
#analiza OTRAMOS_CICS CICS APLICACIONES-OTROS-RAMOS_CICS
#analiza OTRAMOS_CICSD CICSD APLICACIONES-OTROS-RAMOS_CICSD
#analiza OTRAMOS_MODU MODU APLICACIONES-OTROS-RAMOS_MODU
#analiza OTRAMOS_MODUD MODUD APLICACIONES-OTROS-RAMOS_MODUD
#analiza SCASADEC_BATC BATC APLICACIONES-SCA-SALUD-Y-DECESOS_BATC
#analiza SCASADEC_BATCD BATCD APLICACIONES-SCA-SALUD-Y-DECESOS_BATCD
#analiza SCASADEC_CICS CICS APLICACIONES-SCA-SALUD-Y-DECESOS_CICS
#analiza SCASADEC_MODU MODU APLICACIONES-SCA-SALUD-Y-DECESOS_MODU
#analiza SCASADEC_MODUD MODUD APLICACIONES-SCA-SALUD-Y-DECESOS_MODUD
#analiza SINCATLG_BATC BATC SIN-CATALOGAR_BATC
#analiza SINCATLG_BATCD BATCD SIN-CATALOGAR_BATCD
#analiza SINCATLG_CICS CICS SIN-CATALOGAR_CICS
#analiza SINCATLG_CICSD CICSD SIN-CATALOGAR_CICSD
#analiza SINCATLG_MODU MODU SIN-CATALOGAR_MODU
#analiza SINCATLG_MODUD MODUD SIN-CATALOGAR_MODUD
#analiza SINCATLG_MQS MQS SIN-CATALOGAR_MQS
#analiza SINCATLG_MQSBAT MQSBAT SIN-CATALOGAR_MQSBAT
#analiza SISTINFO_BATCD BATCD APLICACIONES-SISTEMAS-DE-INFORMACION_BATCD
#analiza SOPFIN_CICS CICS APLICACIONES-DE-AREAS-DE-SOPORTE-FINANCIERO_CICS
#analiza SOPFIN_MODUD MODUD APLICACIONES-DE-AREAS-DE-SOPORTE-FINANCIERO_MODUD
#analiza TECOPER_BATC BATC TECNOLOGIA-OPERACIONES_BATC
#analiza VIDA_BATC BATC APLICACIONES-VIDA_BATC
#analiza VIDA_BATCD BATCD APLICACIONES-VIDA_BATCD
#analiza VIDA_CICS CICS APLICACIONES-VIDA_CICS
#analiza VIDA_CICSD CICSD APLICACIONES-VIDA_CICSD
#analiza VIDA_MODU MODU APLICACIONES-VIDA_MODU
#analiza VIDA_MODUD MODUD APLICACIONES-VIDA_MODUD
#analiza VIDA_MQS MQS APLICACIONES-VIDA_MQS
